### ISSUE TITLE
0.0.0+192-0bbb6421+20201007-2058 is not compatible with IDEA 2020.3

### ISSUE THREAD

**Issue by mr-git** [disneystreaming/weaver-test#144]
The plugin shows error:
```
Incompatible: requires IDE build 202.* or older
```

**Comment by Baccata** [comment]
@mr-git I've updated the plugin to work on 203, could you check it works ? Thanks in advance

**Comment by mr-git** [comment]
@Baccata, tried it:
```
Plugin "weaver-intellij" was not installed: Request failed with status code 403
```
But IDEA tried to install 0.5.1 :)

Strangely enough, the test runner seems to be running, though there is no more "run using sbt" and "run using UI" checkboxes in configuration of runner...

**Comment by mr-git** [comment]
managed to install the plugin, it seems to be working and integration with IDEAs runner is ok, except for ability to configure runner to use SBT, which is for other ticket, I'd guess

**Comment by mr-git** [comment]
sadly, after restart of IDEA, I am still getting error message about "Plugin installation":
```
Plugin "weaver-intellij" was not installed: 
Request failed with status code 403
```

**Comment by Baccata** [comment]
I'm seeing the same thing :/ 

In the meantime, I guess you can download the plugin's zip and install from disk : 

https://github.com/disneystreaming/weaver-test/releases/download/v0.5.1/weaver-intellij.zip
